name: add-secrets
on: [push, deployment]
  branches:
    release
  jobs:
    add-secrets:
      steps:
        - name: set secrets
          env: # Or as an environment variable
            REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
            REACT_APP_SPOTIFY_CLIENT_SECRET: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_SECRET }}
          run: |
            echo ${#REACT_APP_SPOTIFY_CLIENT_ID}
            echo ${#REACT_APP_SPOTIFY_CLIENT_SECRET}
